# Server configuration
server:
  port: 8080

#Hibernate
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: root


  # V(version)__description.sql
  flyway:
    baseline-on-migrate: true
    baseline-version: 0


  #jpa properties
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: off
    database: postgresql


