# Server configuration
server:
  port: 8080

#Hibernate
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ProjectManager
    username: postgres
    password: root


  # V(version)__description.sql
  flyway:
    schemas: projectManager
    baseline-on-migrate: true


  #jpa properties
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    database: postgresql